#!/usr/bin/env bash
# Launch the Qwen3 rollout stop-token probe on all TPU VM workers.
#
# This is a fast preflight for Qwen GRPO runs such as
# launch_qwen3_simplereward_overfit_128_tpu.sh. It syncs the same rollout/config
# files that control stop-token behavior, then verifies that Qwen rollout config
# defaults to [151643,151645] and that the vanilla sampler stops before
# <|im_end|>.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../../../.." && pwd)"
REMOTE_TOKEN_ENV="$HOME/.cache/tunix/hf_token_env"
DATE_TIME_STR="${DATE_TIME_STR:-$(date -u +%Y%m%dT%H%M%SZ)}"
RUN_LOG_DIR="${RUN_LOG_DIR:-$REPO_ROOT/examples/rl/grpo/logs/${DATE_TIME_STR}_debug_qwen3_rollout_stop_tokens_multihost}"
RUN_LOG_STEM="${RUN_LOG_STEM:-debug_qwen3_rollout_stop_tokens_multihost_${DATE_TIME_STR}}"

MODEL_NAME="${MODEL_NAME:-Qwen3-1.7B-base}"
MAX_NEW_TOKENS="${MAX_NEW_TOKENS:-512}"
MAX_PROMPT_LENGTH="${MAX_PROMPT_LENGTH:-256}"
CACHE_SIZE="${CACHE_SIZE:-}"
TEMPERATURE="${TEMPERATURE:-0.9}"
TOP_P="${TOP_P:-1.0}"
TOP_K="${TOP_K:-50}"
SEED="${SEED:-0}"
MESH_SHAPE="${MESH_SHAPE:-8,4}"
PYTHON_BIN="${PYTHON_BIN:-$HOME/miniconda3/envs/tunix/bin/python}"
TUNIX_JAX_DISTRIBUTED_INIT_TIMEOUT_SECONDS="${TUNIX_JAX_DISTRIBUTED_INIT_TIMEOUT_SECONDS:-300}"
ALLOW_INCONCLUSIVE="${ALLOW_INCONCLUSIVE:-0}"

if [[ -z "${HF_TOKEN:-}" ]]; then
  echo "HF_TOKEN must be set before launching." >&2
  echo "Example: export HF_TOKEN=hf_..." >&2
  exit 1
fi

TPU_ENV=$(curl -sf "http://metadata.google.internal/computeMetadata/v1/instance/attributes/tpu-env" \
  -H "Metadata-Flavor: Google")
TPU_NAME=$(echo "$TPU_ENV" | grep "^NODE_ID:" | awk '{print $2}' | tr -d "'")
ZONE=$(echo "$TPU_ENV" | grep "^ZONE:" | awk '{print $2}' | tr -d "'")

if [[ -z "$TPU_NAME" || -z "$ZONE" ]]; then
  echo "Could not discover TPU_NAME/ZONE from TPU metadata." >&2
  exit 1
fi

echo "[debug-qwen-stop] Preparing TPU slice $TPU_NAME in $ZONE"
echo "[debug-qwen-stop] Logs on each worker: $RUN_LOG_DIR"

tmp_dir=$(mktemp -d)
trap 'rm -rf "$tmp_dir"' EXIT
token_env="$tmp_dir/hf_token_env"
{
  echo "# Generated by launch_debug_qwen3_rollout_stop_tokens_multihost_tpu.sh"
  printf 'export HF_TOKEN=%q\n' "$HF_TOKEN"
} > "$token_env"
chmod 600 "$token_env"

gcloud compute tpus tpu-vm ssh "$TPU_NAME" \
  --zone="$ZONE" \
  --worker=all \
  --command="mkdir -p '$HOME/.cache/tunix' '$SCRIPT_DIR' '$RUN_LOG_DIR' && chmod 700 '$HOME/.cache/tunix'"

gcloud compute tpus tpu-vm scp "$token_env" "$TPU_NAME:$REMOTE_TOKEN_ENV" \
  --zone="$ZONE" \
  --worker=all

gcloud compute tpus tpu-vm ssh "$TPU_NAME" \
  --zone="$ZONE" \
  --worker=all \
  --command="chmod 600 '$REMOTE_TOKEN_ENV'"

for file_to_sync in \
  "$SCRIPT_DIR/debug_qwen3_rollout_stop_tokens.py" \
  "$SCRIPT_DIR/run_debug_qwen3_rollout_stop_tokens.sh" \
  "$SCRIPT_DIR/launch_debug_qwen3_rollout_stop_tokens_multihost_tpu.sh" \
  "$REPO_ROOT/tunix/cli/grpo_main.py" \
  "$REPO_ROOT/tunix/cli/config.py" \
  "$REPO_ROOT/tunix/generate/sampler.py" \
  "$REPO_ROOT/tunix/rl/rollout/base_rollout.py" \
  "$REPO_ROOT/tunix/rl/rollout/vanilla_rollout.py"; do
  gcloud compute tpus tpu-vm scp "$file_to_sync" "$TPU_NAME:$file_to_sync" \
    --zone="$ZONE" \
    --worker=all
done

EXTRA_PYTHON_ARGS="${EXTRA_PYTHON_ARGS:-}"
if [[ -n "$CACHE_SIZE" ]]; then
  EXTRA_PYTHON_ARGS="$EXTRA_PYTHON_ARGS --cache-size '$CACHE_SIZE'"
fi
if [[ "$ALLOW_INCONCLUSIVE" == "1" ]]; then
  EXTRA_PYTHON_ARGS="$EXTRA_PYTHON_ARGS --allow-inconclusive"
fi

REMOTE_CMD="set -euo pipefail; source '$REMOTE_TOKEN_ENV'; mkdir -p '$RUN_LOG_DIR' \"\$HOME/tpu_logs\"; chmod 700 \"\$HOME/tpu_logs\"; worker_log='$RUN_LOG_DIR/${RUN_LOG_STEM}_worker_'\$(hostname -s 2>/dev/null || hostname)'.log'; exec > >(tee -a \"\$worker_log\") 2>&1; echo '[debug-qwen-stop] worker log:' \"\$worker_log\"; export TPU_LOG_DIR=\"\$HOME/tpu_logs\"; export PYTHONPATH='$REPO_ROOT':\${PYTHONPATH:-}; export JAX_PLATFORMS=tpu; export TUNIX_JAX_DISTRIBUTED_AUTO_INIT=1; export TUNIX_JAX_DISTRIBUTED_INIT_TIMEOUT_SECONDS='$TUNIX_JAX_DISTRIBUTED_INIT_TIMEOUT_SECONDS'; cd '$REPO_ROOT'; '$PYTHON_BIN' '$SCRIPT_DIR/debug_qwen3_rollout_stop_tokens.py' --model-name '$MODEL_NAME' --max-new-tokens '$MAX_NEW_TOKENS' --max-prompt-length '$MAX_PROMPT_LENGTH' --temperature '$TEMPERATURE' --top-p '$TOP_P' --top-k '$TOP_K' --seed '$SEED' --mesh-shape '$MESH_SHAPE' $EXTRA_PYTHON_ARGS"

echo "[debug-qwen-stop] Launching stop-token probe on all workers..."
gcloud compute tpus tpu-vm ssh "$TPU_NAME" \
  --zone="$ZONE" \
  --worker=all \
  --command="bash -lc $(printf '%q' "$REMOTE_CMD")"
