#!/usr/bin/env bash
# Launch the standalone Tunix Qwen3 logits/vanilla-sampler probe on all TPU VM
# workers. Each worker joins JAX distributed initialization and writes its own
# log, so we can compare top logits/completions by host/process.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../../../.." && pwd)"
REMOTE_TOKEN_ENV="$HOME/.cache/tunix/hf_token_env"
DATE_TIME_STR="${DATE_TIME_STR:-$(date -u +%Y%m%dT%H%M%SZ)}"
RUN_LOG_DIR="${RUN_LOG_DIR:-$REPO_ROOT/examples/rl/grpo/logs/${DATE_TIME_STR}_debug_tunix_qwen3_logits_multihost}"
RUN_LOG_STEM="${RUN_LOG_STEM:-debug_tunix_qwen3_logits_multihost_${DATE_TIME_STR}}"

MODEL_NAME="${MODEL_NAME:-Qwen3-1.7B}"
PROMPT="${PROMPT:-What is 2+2?}"
MAX_NEW_TOKENS="${MAX_NEW_TOKENS:-32}"
REPEAT_PROMPTS="${REPEAT_PROMPTS:-8}"
MAX_PROMPT_LENGTH="${MAX_PROMPT_LENGTH:-256}"
CACHE_SIZE="${CACHE_SIZE:-512}"
TOP_K_LOGITS="${TOP_K_LOGITS:-20}"
MESH_SHAPE="${MESH_SHAPE:-8,4}"
PYTHON_BIN="${PYTHON_BIN:-$HOME/miniconda3/envs/tunix/bin/python}"
TUNIX_JAX_DISTRIBUTED_INIT_TIMEOUT_SECONDS="${TUNIX_JAX_DISTRIBUTED_INIT_TIMEOUT_SECONDS:-300}"

if [[ -z "${HF_TOKEN:-}" ]]; then
  echo "HF_TOKEN must be set before launching." >&2
  echo "Example: export HF_TOKEN=hf_..." >&2
  exit 1
fi

TPU_ENV=$(curl -sf "http://metadata.google.internal/computeMetadata/v1/instance/attributes/tpu-env" \
  -H "Metadata-Flavor: Google")
TPU_NAME=$(echo "$TPU_ENV" | grep "^NODE_ID:" | awk '{print $2}' | tr -d "'")
ZONE=$(echo "$TPU_ENV" | grep "^ZONE:" | awk '{print $2}' | tr -d "'")

if [[ -z "$TPU_NAME" || -z "$ZONE" ]]; then
  echo "Could not discover TPU_NAME/ZONE from TPU metadata." >&2
  exit 1
fi

echo "[debug-tunix-logits] Preparing TPU slice $TPU_NAME in $ZONE"
echo "[debug-tunix-logits] Logs on each worker: $RUN_LOG_DIR"

tmp_dir=$(mktemp -d)
trap 'rm -rf "$tmp_dir"' EXIT
token_env="$tmp_dir/hf_token_env"
{
  echo "# Generated by launch_debug_tunix_qwen3_logits_multihost_tpu.sh"
  printf 'export HF_TOKEN=%q\n' "$HF_TOKEN"
} > "$token_env"
chmod 600 "$token_env"

gcloud compute tpus tpu-vm ssh "$TPU_NAME" \
  --zone="$ZONE" \
  --worker=all \
  --command="mkdir -p '$HOME/.cache/tunix' '$SCRIPT_DIR' '$RUN_LOG_DIR' && chmod 700 '$HOME/.cache/tunix'"

gcloud compute tpus tpu-vm scp "$token_env" "$TPU_NAME:$REMOTE_TOKEN_ENV" \
  --zone="$ZONE" \
  --worker=all

gcloud compute tpus tpu-vm ssh "$TPU_NAME" \
  --zone="$ZONE" \
  --worker=all \
  --command="chmod 600 '$REMOTE_TOKEN_ENV'"

for file_to_sync in \
  "$SCRIPT_DIR/debug_tunix_qwen3_logits.py" \
  "$SCRIPT_DIR/run_debug_tunix_qwen3_logits.sh" \
  "$SCRIPT_DIR/launch_debug_tunix_qwen3_logits_multihost_tpu.sh" \
  "$REPO_ROOT/tunix/generate/sampler.py"; do
  gcloud compute tpus tpu-vm scp "$file_to_sync" "$TPU_NAME:$file_to_sync" \
    --zone="$ZONE" \
    --worker=all
done

printf -v quoted_prompt "%q" "$PROMPT"
EXTRA_PYTHON_ARGS="${EXTRA_PYTHON_ARGS:-}"
TUNIX_SAMPLER_DEBUG_SHARDS="${TUNIX_SAMPLER_DEBUG_SHARDS:-0}"
REMOTE_CMD="set -euo pipefail; source '$REMOTE_TOKEN_ENV'; mkdir -p '$RUN_LOG_DIR' \"\$HOME/tpu_logs\"; chmod 700 \"\$HOME/tpu_logs\"; worker_log='$RUN_LOG_DIR/${RUN_LOG_STEM}_worker_'\$(hostname -s 2>/dev/null || hostname)'.log'; exec > >(tee -a \"\$worker_log\") 2>&1; echo '[debug-tunix-logits] worker log:' \"\$worker_log\"; export TPU_LOG_DIR=\"\$HOME/tpu_logs\"; export PYTHONPATH='$REPO_ROOT':\${PYTHONPATH:-}; export JAX_PLATFORMS=tpu; export TUNIX_JAX_DISTRIBUTED_AUTO_INIT=1; export TUNIX_JAX_DISTRIBUTED_INIT_TIMEOUT_SECONDS='$TUNIX_JAX_DISTRIBUTED_INIT_TIMEOUT_SECONDS'; export TUNIX_SAMPLER_DEBUG_SHARDS='$TUNIX_SAMPLER_DEBUG_SHARDS'; cd '$REPO_ROOT'; '$PYTHON_BIN' '$SCRIPT_DIR/debug_tunix_qwen3_logits.py' --model-name '$MODEL_NAME' --prompt $quoted_prompt --repeat-prompts '$REPEAT_PROMPTS' --max-new-tokens '$MAX_NEW_TOKENS' --max-prompt-length '$MAX_PROMPT_LENGTH' --cache-size '$CACHE_SIZE' --top-k-logits '$TOP_K_LOGITS' --mesh-shape '$MESH_SHAPE' $EXTRA_PYTHON_ARGS"

echo "[debug-tunix-logits] Launching probe on all workers..."
gcloud compute tpus tpu-vm ssh "$TPU_NAME" \
  --zone="$ZONE" \
  --worker=all \
  --command="bash -lc $(printf '%q' "$REMOTE_CMD")"
