#!/usr/bin/env bash
# Launch a multi-host Qwen3 GRPO FULL fine-tuning run with long-generation
# (max_new_tokens=8096) on a TPU VM slice.
#
# This is a sibling of launch_qwen3_simplereward_rollout_probe_tpu.sh but
# configured for real training: multi-host-safe prompt batches, gradient
# accumulation to keep the compiled micro-batch small, periodic checkpointing,
# aggressive logging, full fine-tuning (no LoRA), and a generation length that
# exercises the long-context KV cache path. It uses the vanilla rollout engine.
#
# Usage:
#   export HF_TOKEN=...
#   bash /home/gs1693/repo/tunix/examples/rl/grpo/gsm8k/launch_qwen3_simplereward_fulltrain_tpu.sh
#
# Overrides:
#   batch_size=32 mini_batch_size=32 train_micro_batch_size=8 \
#     actor_train_completion_micro_batch_size=1 \
#     num_generations=4 total_generation_steps=8096 max_steps=4000 \
#     bash launch_qwen3_simplereward_fulltrain_tpu.sh
#
# Logs:
#   - shell:        $REPO_ROOT/examples/rl/grpo/logs/${DATE_TIME_STR}_qwen3_simplereward_fulltrain_multihost
#   - tensorboard:  $BUCKET_MOUNT_POINT/tunix_runs/grpo_gsm8k_qwen3_simplereward_fulltrain/${DATE_TIME_STR}/tensorboard
#   - checkpoints:  $BUCKET_MOUNT_POINT/tunix_runs/grpo_gsm8k_qwen3_simplereward_fulltrain/${DATE_TIME_STR}/checkpoints
#   - trajectories: $BUCKET_MOUNT_POINT/tunix_runs/grpo_gsm8k_qwen3_simplereward_fulltrain/${DATE_TIME_STR}/trajectories

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TRAIN_SCRIPT="$SCRIPT_DIR/run_qwen3_simplereward_fulltrain.sh"
PREFLIGHT_SCRIPT="$SCRIPT_DIR/jax_tpu_preflight.py"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../../.." && pwd)"
MOUNT_SCRIPT="$REPO_ROOT/mount_bucket.sh"
SAMPLER="$REPO_ROOT/tunix/generate/sampler.py"
VANILLA_ROLLOUT="$REPO_ROOT/tunix/rl/rollout/vanilla_rollout.py"
VLLM_SAMPLER="$REPO_ROOT/tunix/generate/vllm_sampler.py"
SHARDING_UTILS="$REPO_ROOT/tunix/sft/sharding_utils.py"
RL_COMMON="$REPO_ROOT/tunix/rl/common.py"
RL_TRAINER="$REPO_ROOT/tunix/rl/trainer.py"
RL_LEARNER="$REPO_ROOT/tunix/rl/rl_learner.py"
RL_CLUSTER="$REPO_ROOT/tunix/rl/rl_cluster.py"
GRPO_LEARNER="$REPO_ROOT/tunix/rl/grpo/grpo_learner.py"
PEFT_TRAINER="$REPO_ROOT/tunix/sft/peft_trainer.py"
GRPO_MAIN="$REPO_ROOT/tunix/cli/grpo_main.py"
CLI_CONFIG="$REPO_ROOT/tunix/cli/config.py"
DATA_UTILS="$REPO_ROOT/tunix/cli/utils/data.py"
MATH_DATASET="$REPO_ROOT/tunix/examples/data/math_dataset.py"
REMOTE_TOKEN_ENV="$HOME/.cache/tunix/hf_token_env"
CLEAN_STALE_TPU_STATE="${CLEAN_STALE_TPU_STATE:-1}"
CHECK_TPU_VFIO_BUSY="${CHECK_TPU_VFIO_BUSY:-1}"
RUN_TPU_PREFLIGHT="${RUN_TPU_PREFLIGHT:-1}"
TPU_PREFLIGHT_TIMEOUT_SECONDS="${TPU_PREFLIGHT_TIMEOUT_SECONDS:-180}"
TPU_PREFLIGHT_HOLD_SECONDS="${TPU_PREFLIGHT_HOLD_SECONDS:-30}"
num_generations="${num_generations:-4}"
if [[ "$num_generations" == "4" ]]; then
  actor_train_completion_micro_batch_size="${actor_train_completion_micro_batch_size:-1}"
fi

if [[ -z "${HF_TOKEN:-}" ]]; then
  echo "HF_TOKEN must be set before launching." >&2
  echo "Example: export HF_TOKEN=hf_..." >&2
  exit 1
fi

for required_file in "$TRAIN_SCRIPT" "$PREFLIGHT_SCRIPT" "$MOUNT_SCRIPT" "$SAMPLER" "$VANILLA_ROLLOUT" "$VLLM_SAMPLER" "$SHARDING_UTILS" "$RL_COMMON" "$RL_TRAINER" "$RL_LEARNER" "$RL_CLUSTER" "$GRPO_LEARNER" "$PEFT_TRAINER" "$GRPO_MAIN" "$CLI_CONFIG" "$DATA_UTILS" "$MATH_DATASET"; do
  if [[ ! -f "$required_file" ]]; then
    echo "Required file not found: $required_file" >&2
    exit 1
  fi
done

TPU_ENV=$(curl -sf "http://metadata.google.internal/computeMetadata/v1/instance/attributes/tpu-env" \
  -H "Metadata-Flavor: Google")
TPU_NAME=$(echo "$TPU_ENV" | grep "^NODE_ID:" | awk '{print $2}' | tr -d "'")
ZONE=$(echo "$TPU_ENV" | grep "^ZONE:" | awk '{print $2}' | tr -d "'")

if [[ -z "$TPU_NAME" || -z "$ZONE" ]]; then
  echo "Could not discover TPU_NAME/ZONE from TPU metadata." >&2
  exit 1
fi

echo "[fulltrain] Preparing TPU slice $TPU_NAME in $ZONE"

tmp_dir=$(mktemp -d)
trap 'rm -rf "$tmp_dir"' EXIT
token_env="$tmp_dir/hf_token_env"
{
  echo "# Generated by launch_qwen3_simplereward_fulltrain_tpu.sh"
  printf 'export HF_TOKEN=%q\n' "$HF_TOKEN"
} > "$token_env"
chmod 600 "$token_env"

echo "[fulltrain] Creating per-worker token env path and syncing files"
gcloud compute tpus tpu-vm ssh "$TPU_NAME" \
  --zone="$ZONE" \
  --worker=all \
  --command="mkdir -p '$HOME/.cache/tunix' '$SCRIPT_DIR' && chmod 700 '$HOME/.cache/tunix'"

gcloud compute tpus tpu-vm scp "$token_env" "$TPU_NAME:$REMOTE_TOKEN_ENV" \
  --zone="$ZONE" \
  --worker=all

gcloud compute tpus tpu-vm ssh "$TPU_NAME" \
  --zone="$ZONE" \
  --worker=all \
  --command="chmod 600 '$REMOTE_TOKEN_ENV'"

for file_to_sync in "$TRAIN_SCRIPT" "$PREFLIGHT_SCRIPT" "$MOUNT_SCRIPT" "$SAMPLER" "$VANILLA_ROLLOUT" "$VLLM_SAMPLER" "$SHARDING_UTILS" "$RL_COMMON" "$RL_TRAINER" "$RL_LEARNER" "$RL_CLUSTER" "$GRPO_LEARNER" "$PEFT_TRAINER" "$GRPO_MAIN" "$CLI_CONFIG" "$DATA_UTILS" "$MATH_DATASET"; do
  gcloud compute tpus tpu-vm scp "$file_to_sync" "$TPU_NAME:$file_to_sync" \
    --zone="$ZONE" \
    --worker=all
done

if [[ "$CLEAN_STALE_TPU_STATE" == "1" ]]; then
  echo "[fulltrain] Cleaning stale Ray/libtpu state with sudo"
  gcloud compute tpus tpu-vm ssh "$TPU_NAME" \
    --zone="$ZONE" \
    --worker=all \
    --command='bash -lc '"'"'
set -euo pipefail
current_user="$(id -un)"
if ps -eo user=,pid=,stat=,etime=,comm=,args= | awk -v user="$current_user" "\$1 == user && \$0 !~ /google-cloud-cli|gcloud.py|compute tpus tpu-vm ssh/ && \$5 ~ /python|vllm/ && \$0 ~ /python3 -m tunix|grpo_main|vllm/ {found=1} END {exit !found}"; then
  echo "Active $current_user Tunix/vLLM process detected on $(hostname); refusing cleanup." >&2
  exit 1
fi
sudo pkill -TERM -u linrong -f qwen3vl-inference || true
sudo pkill -TERM -u linrong -f gcs_server || true
sleep 2
sudo pkill -KILL -u linrong -f qwen3vl-inference || true
sudo pkill -KILL -u linrong -f gcs_server || true
sudo rm -f /tmp/libtpu_lockfile
sudo rm -rf /tmp/ray
echo "cleaned $(hostname)"
'"'"''
else
  echo "[fulltrain] Skipping stale TPU state cleanup because CLEAN_STALE_TPU_STATE=0"
fi

if [[ "$CHECK_TPU_VFIO_BUSY" == "1" ]]; then
  echo "[fulltrain] Checking TPU VFIO devices are free"
  gcloud compute tpus tpu-vm ssh "$TPU_NAME" \
    --zone="$ZONE" \
    --worker=all \
    --command='bash -lc '"'"'
set -euo pipefail
tmp="$(mktemp)"
if sudo lsof -w /dev/vfio/* > "$tmp" 2>/dev/null; then
  echo "TPU device is still busy on $(hostname):" >&2
  cat "$tmp" >&2
  rm -f "$tmp"
  exit 1
fi
rm -f "$tmp"
echo "vfio-free $(hostname)"
'"'"''
else
  echo "[fulltrain] Skipping TPU VFIO busy check because CHECK_TPU_VFIO_BUSY=0"
fi

echo "[fulltrain] Verifying synced worker prerequisites"
gcloud compute tpus tpu-vm ssh "$TPU_NAME" \
  --zone="$ZONE" \
  --worker=all \
  --command="bash -lc 'test -f \"$TRAIN_SCRIPT\" && test -f \"$MOUNT_SCRIPT\" && test -x \"$HOME/miniconda3/envs/tunix/bin/python\" && test -f \"$REMOTE_TOKEN_ENV\" && echo ready \$(hostname)'"

if [[ "$RUN_TPU_PREFLIGHT" == "1" ]]; then
  echo "[fulltrain] Running bounded all-worker JAX TPU preflight"
  gcloud compute tpus tpu-vm ssh "$TPU_NAME" \
    --zone="$ZONE" \
    --worker=all \
    --command="bash -lc 'set -euo pipefail; mkdir -p \"\$HOME/tpu_logs\"; chmod 700 \"\$HOME/tpu_logs\"; export TPU_LOG_DIR=\"\$HOME/tpu_logs\"; export TPU_PREFLIGHT_HOLD_SECONDS=\"$TPU_PREFLIGHT_HOLD_SECONDS\"; timeout \"$TPU_PREFLIGHT_TIMEOUT_SECONDS\" \"\$HOME/miniconda3/envs/tunix/bin/python\" \"$PREFLIGHT_SCRIPT\"'"
else
  echo "[fulltrain] Skipping JAX TPU preflight because RUN_TPU_PREFLIGHT=0"
fi

echo "[fulltrain] Launching full fine-tuning run"
cd "$REPO_ROOT"
HF_TOKEN_ENV_FILE="$REMOTE_TOKEN_ENV" \
  num_generations="$num_generations" \
  actor_train_completion_micro_batch_size="${actor_train_completion_micro_batch_size:-}" \
  bash "$TRAIN_SCRIPT"
