#!/usr/bin/env bash
# Prepare this TPU VM slice and launch Qwen3 GRPO simple-reward training.
#
# Usage:
#   export HF_TOKEN=...
#   bash /home/gs1693/repo/tunix/examples/rl/grpo/gsm8k/launch_qwen3_simplereward_tpu.sh
#
# Optional overrides:
#   model_name=Qwen3-1.7B-base batch_size=1 num_batches=1 train_fraction=1.0 \
#     bash /home/gs1693/repo/tunix/examples/rl/grpo/gsm8k/launch_qwen3_simplereward_tpu.sh
#
# Set CLEAN_STALE_TPU_STATE=0 to skip the sudo cleanup step.
# Set RUN_TPU_PREFLIGHT=0 to skip the bounded all-worker JAX init check.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TRAIN_SCRIPT="$SCRIPT_DIR/run_qwen3_simplereward.sh"
PREFLIGHT_SCRIPT="$SCRIPT_DIR/jax_tpu_preflight.py"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../../.." && pwd)"
VLLM_SAMPLER="$REPO_ROOT/tunix/generate/vllm_sampler.py"
REMOTE_TOKEN_ENV="$HOME/.cache/tunix/hf_token_env"
CLEAN_STALE_TPU_STATE="${CLEAN_STALE_TPU_STATE:-1}"
CHECK_TPU_VFIO_BUSY="${CHECK_TPU_VFIO_BUSY:-1}"
RUN_TPU_PREFLIGHT="${RUN_TPU_PREFLIGHT:-1}"
TPU_PREFLIGHT_TIMEOUT_SECONDS="${TPU_PREFLIGHT_TIMEOUT_SECONDS:-180}"
TPU_PREFLIGHT_HOLD_SECONDS="${TPU_PREFLIGHT_HOLD_SECONDS:-60}"

if [[ -z "${HF_TOKEN:-}" ]]; then
  echo "HF_TOKEN must be set before launching." >&2
  echo "Example: export HF_TOKEN=hf_..." >&2
  exit 1
fi

if [[ ! -f "$TRAIN_SCRIPT" ]]; then
  echo "Training script not found: $TRAIN_SCRIPT" >&2
  exit 1
fi

if [[ ! -f "$PREFLIGHT_SCRIPT" ]]; then
  echo "Preflight script not found: $PREFLIGHT_SCRIPT" >&2
  exit 1
fi

if [[ ! -f "$VLLM_SAMPLER" ]]; then
  echo "vLLM sampler not found: $VLLM_SAMPLER" >&2
  exit 1
fi

TPU_ENV=$(curl -sf "http://metadata.google.internal/computeMetadata/v1/instance/attributes/tpu-env" \
  -H "Metadata-Flavor: Google")
TPU_NAME=$(echo "$TPU_ENV" | grep "^NODE_ID:" | awk '{print $2}' | tr -d "'")
ZONE=$(echo "$TPU_ENV" | grep "^ZONE:" | awk '{print $2}' | tr -d "'")

if [[ -z "$TPU_NAME" || -z "$ZONE" ]]; then
  echo "Could not discover TPU_NAME/ZONE from TPU metadata." >&2
  exit 1
fi

echo "Preparing TPU slice $TPU_NAME in $ZONE"

tmp_dir=$(mktemp -d)
trap 'rm -rf "$tmp_dir"' EXIT
token_env="$tmp_dir/hf_token_env"
{
  echo "# Generated by launch_qwen3_simplereward_tpu.sh"
  printf 'export HF_TOKEN=%q\n' "$HF_TOKEN"
} > "$token_env"
chmod 600 "$token_env"

echo "Creating per-worker token env path and syncing launch files"
gcloud compute tpus tpu-vm ssh "$TPU_NAME" \
  --zone="$ZONE" \
  --worker=all \
  --command="mkdir -p '$HOME/.cache/tunix' '$SCRIPT_DIR' && chmod 700 '$HOME/.cache/tunix'"

gcloud compute tpus tpu-vm scp "$token_env" "$TPU_NAME:$REMOTE_TOKEN_ENV" \
  --zone="$ZONE" \
  --worker=all

gcloud compute tpus tpu-vm ssh "$TPU_NAME" \
  --zone="$ZONE" \
  --worker=all \
  --command="chmod 600 '$REMOTE_TOKEN_ENV'"

gcloud compute tpus tpu-vm scp "$TRAIN_SCRIPT" "$TPU_NAME:$TRAIN_SCRIPT" \
  --zone="$ZONE" \
  --worker=all

gcloud compute tpus tpu-vm scp "$PREFLIGHT_SCRIPT" "$TPU_NAME:$PREFLIGHT_SCRIPT" \
  --zone="$ZONE" \
  --worker=all

gcloud compute tpus tpu-vm scp "$VLLM_SAMPLER" "$TPU_NAME:$VLLM_SAMPLER" \
  --zone="$ZONE" \
  --worker=all

if [[ "$CLEAN_STALE_TPU_STATE" == "1" ]]; then
  echo "Cleaning stale old-Ray/libtpu state with sudo"
  gcloud compute tpus tpu-vm ssh "$TPU_NAME" \
    --zone="$ZONE" \
    --worker=all \
    --command='bash -lc '"'"'
set -euo pipefail
current_user="$(id -un)"
if ps -eo user=,pid=,stat=,etime=,comm=,args= | awk -v user="$current_user" "\$1 == user && \$0 !~ /google-cloud-cli|gcloud.py|compute tpus tpu-vm ssh/ && \$5 ~ /python|vllm/ && \$0 ~ /python3 -m tunix|grpo_main|vllm/ {found=1} END {exit !found}"; then
  echo "Active $current_user Tunix/vLLM process detected on $(hostname); refusing cleanup." >&2
  exit 1
fi
sudo pkill -TERM -u linrong -f qwen3vl-inference || true
sudo pkill -TERM -u linrong -f gcs_server || true
sleep 2
sudo pkill -KILL -u linrong -f qwen3vl-inference || true
sudo pkill -KILL -u linrong -f gcs_server || true
sudo rm -f /tmp/libtpu_lockfile
sudo rm -rf /tmp/ray
if ps -eo user=,pid=,stat=,etime=,comm=,args= | awk "\$1 == \"linrong\" && \$5 ~ /python|gcs_server|ray/ && \$0 ~ /qwen3vl-inference|gcs_server/ {found=1} END {exit !found}"; then
  echo "Stale linrong Ray/vLLM process still alive on $(hostname)." >&2
  ps -eo user=,pid=,stat=,etime=,comm=,args= | awk "\$1 == \"linrong\" && \$5 ~ /python|gcs_server|ray/ && \$0 ~ /qwen3vl-inference|gcs_server/ {print}" >&2 || true
  exit 1
fi
echo "cleaned $(hostname)"
'"'"''
else
  echo "Skipping stale TPU state cleanup because CLEAN_STALE_TPU_STATE=0"
fi

if [[ "$CHECK_TPU_VFIO_BUSY" == "1" ]]; then
  echo "Checking TPU VFIO devices are free"
  gcloud compute tpus tpu-vm ssh "$TPU_NAME" \
    --zone="$ZONE" \
    --worker=all \
    --command='bash -lc '"'"'
set -euo pipefail
tmp="$(mktemp)"
if sudo lsof -w /dev/vfio/* > "$tmp" 2>/dev/null; then
  echo "TPU device is still busy on $(hostname):" >&2
  cat "$tmp" >&2
  rm -f "$tmp"
  exit 1
fi
rm -f "$tmp"
echo "vfio-free $(hostname)"
'"'"''
else
  echo "Skipping TPU VFIO busy check because CHECK_TPU_VFIO_BUSY=0"
fi

echo "Verifying synced worker prerequisites"
gcloud compute tpus tpu-vm ssh "$TPU_NAME" \
  --zone="$ZONE" \
  --worker=all \
  --command="bash -lc 'test -f \"$TRAIN_SCRIPT\" && test -x \"$HOME/miniconda3/envs/tunix/bin/python\" && test -f \"$REMOTE_TOKEN_ENV\" && echo ready \$(hostname)'"

if [[ "$RUN_TPU_PREFLIGHT" == "1" ]]; then
  echo "Running bounded all-worker JAX TPU preflight"
  gcloud compute tpus tpu-vm ssh "$TPU_NAME" \
    --zone="$ZONE" \
    --worker=all \
    --command="bash -lc 'set -euo pipefail; mkdir -p \"\$HOME/tpu_logs\"; chmod 700 \"\$HOME/tpu_logs\"; export TPU_LOG_DIR=\"\$HOME/tpu_logs\"; export TPU_PREFLIGHT_HOLD_SECONDS=\"$TPU_PREFLIGHT_HOLD_SECONDS\"; timeout \"$TPU_PREFLIGHT_TIMEOUT_SECONDS\" \"\$HOME/miniconda3/envs/tunix/bin/python\" \"$PREFLIGHT_SCRIPT\"'"
else
  echo "Skipping JAX TPU preflight because RUN_TPU_PREFLIGHT=0"
fi

echo "Launching training"
cd "$REPO_ROOT"
HF_TOKEN_ENV_FILE="$REMOTE_TOKEN_ENV" bash "$TRAIN_SCRIPT"
