#!/usr/bin/env bash
# Launch a standalone vLLM TPU inference probe.
#
# Usage:
#   export HF_TOKEN=...
#   bash /home/gs1693/repo/tunix/examples/rl/grpo/gsm8k/launch_debug_vllm_inference_tpu.sh
#
# Useful tiny overrides:
#   VLLM_DEBUG_MAX_MODEL_LEN=128 \
#   VLLM_DEBUG_MAX_NUM_BATCHED_TOKENS=128 \
#   VLLM_DEBUG_MAX_GENERATION_STEPS=16 \
#   bash /home/gs1693/repo/tunix/examples/rl/grpo/gsm8k/launch_debug_vllm_inference_tpu.sh
#
# By default all TPU VM workers join JAX initialization, but only worker 0 runs
# vLLM. Use VLLM_DEBUG_WORKERS=all for the previous all-worker stress behavior,
# or VLLM_DEBUG_WORKERS=0,1,2 to activate each worker sequentially.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEBUG_SCRIPT="$SCRIPT_DIR/debug_vllm_inference_tpu.py"
PREFLIGHT_SCRIPT="$SCRIPT_DIR/jax_tpu_preflight.py"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../../.." && pwd)"
VLLM_SAMPLER="$REPO_ROOT/tunix/generate/vllm_sampler.py"
VLLM_ASYNC_DRIVER="$REPO_ROOT/tunix/generate/vllm_async_driver.py"
TOKENIZER_ADAPTER="$REPO_ROOT/tunix/generate/tokenizer_adapter.py"
REMOTE_TOKEN_ENV="$HOME/.cache/tunix/hf_token_env"
CLEAN_STALE_TPU_STATE="${CLEAN_STALE_TPU_STATE:-1}"
CHECK_TPU_VFIO_BUSY="${CHECK_TPU_VFIO_BUSY:-1}"
RUN_TPU_PREFLIGHT="${RUN_TPU_PREFLIGHT:-1}"
ALLOW_TPU_PREFLIGHT_FAILURE="${ALLOW_TPU_PREFLIGHT_FAILURE:-1}"
VLLM_DEBUG_WORKERS="${VLLM_DEBUG_WORKERS:-0}"
VLLM_DEBUG_CONTINUE_ON_WORKER_FAILURE="${VLLM_DEBUG_CONTINUE_ON_WORKER_FAILURE:-0}"
VLLM_DEBUG_PARTICIPANT_HOLD_SECONDS="${VLLM_DEBUG_PARTICIPANT_HOLD_SECONDS:-900}"
TPU_PREFLIGHT_TIMEOUT_SECONDS="${TPU_PREFLIGHT_TIMEOUT_SECONDS:-180}"
TPU_PREFLIGHT_HOLD_SECONDS="${TPU_PREFLIGHT_HOLD_SECONDS:-15}"
DATE_TIME_STR="${DATE_TIME_STR:-$(date -u +%Y%m%dT%H%M%SZ)}"
RUN_LOG_DIR="${RUN_LOG_DIR:-$REPO_ROOT/examples/rl/grpo/logs/${DATE_TIME_STR}_vllm_standalone_debug}"
RUN_LOG_STEM="${RUN_LOG_STEM:-vllm_standalone_debug_${DATE_TIME_STR}}"
LAUNCHER_LOG="$RUN_LOG_DIR/${RUN_LOG_STEM}_launcher_$(hostname -s 2>/dev/null || hostname).log"

mkdir -p "$RUN_LOG_DIR"
exec > >(tee -a "$LAUNCHER_LOG") 2>&1

if [[ -z "${HF_TOKEN:-}" ]]; then
  echo "HF_TOKEN must be set before launching." >&2
  echo "Example: export HF_TOKEN=hf_..." >&2
  exit 1
fi

for required_file in "$DEBUG_SCRIPT" "$PREFLIGHT_SCRIPT" "$VLLM_SAMPLER" "$VLLM_ASYNC_DRIVER" "$TOKENIZER_ADAPTER"; do
  if [[ ! -f "$required_file" ]]; then
    echo "Required file not found: $required_file" >&2
    exit 1
  fi
done

TPU_ENV=$(curl -sf "http://metadata.google.internal/computeMetadata/v1/instance/attributes/tpu-env" \
  -H "Metadata-Flavor: Google")
TPU_NAME=$(echo "$TPU_ENV" | grep "^NODE_ID:" | awk '{print $2}' | tr -d "'")
ZONE=$(echo "$TPU_ENV" | grep "^ZONE:" | awk '{print $2}' | tr -d "'")

if [[ -z "$TPU_NAME" || -z "$ZONE" ]]; then
  echo "Could not discover TPU_NAME/ZONE from TPU metadata." >&2
  exit 1
fi

echo "[vllm-debug] Preparing TPU slice $TPU_NAME in $ZONE"
echo "[vllm-debug] Aggregate launcher log: $LAUNCHER_LOG"
echo "[vllm-debug] Active vLLM worker setting: $VLLM_DEBUG_WORKERS"
echo "[vllm-debug] Per-worker log path on each worker: $RUN_LOG_DIR/${RUN_LOG_STEM}_worker_<hostname>.log"

tmp_dir=$(mktemp -d)
trap 'rm -rf "$tmp_dir"' EXIT
token_env="$tmp_dir/hf_token_env"
{
  echo "# Generated by launch_debug_vllm_inference_tpu.sh"
  printf 'export HF_TOKEN=%q\n' "$HF_TOKEN"
} > "$token_env"
chmod 600 "$token_env"

echo "[vllm-debug] Creating token env and syncing probe files"
gcloud compute tpus tpu-vm ssh "$TPU_NAME" \
  --zone="$ZONE" \
  --worker=all \
  --command="mkdir -p '$HOME/.cache/tunix' '$SCRIPT_DIR' '$RUN_LOG_DIR' && chmod 700 '$HOME/.cache/tunix'"

gcloud compute tpus tpu-vm scp "$token_env" "$TPU_NAME:$REMOTE_TOKEN_ENV" \
  --zone="$ZONE" \
  --worker=all

gcloud compute tpus tpu-vm ssh "$TPU_NAME" \
  --zone="$ZONE" \
  --worker=all \
  --command="chmod 600 '$REMOTE_TOKEN_ENV'"

for file_to_sync in "$DEBUG_SCRIPT" "$PREFLIGHT_SCRIPT" "$VLLM_SAMPLER" "$VLLM_ASYNC_DRIVER" "$TOKENIZER_ADAPTER"; do
  gcloud compute tpus tpu-vm scp "$file_to_sync" "$TPU_NAME:$file_to_sync" \
    --zone="$ZONE" \
    --worker=all
done

if [[ "$CLEAN_STALE_TPU_STATE" == "1" ]]; then
  echo "[vllm-debug] Cleaning stale Ray/libtpu state with sudo"
  gcloud compute tpus tpu-vm ssh "$TPU_NAME" \
    --zone="$ZONE" \
    --worker=all \
    --command='bash -lc '"'"'
set -euo pipefail
current_user="$(id -un)"
if ps -eo user=,pid=,stat=,etime=,comm=,args= | awk -v user="$current_user" "\$1 == user && \$0 !~ /google-cloud-cli|gcloud.py|compute tpus tpu-vm ssh/ && \$5 ~ /python|vllm/ && \$0 ~ /python3 -m tunix|grpo_main|debug_vllm_inference_tpu|vllm/ {found=1} END {exit !found}"; then
  echo "Active $current_user Tunix/vLLM process detected on $(hostname); refusing cleanup." >&2
  exit 1
fi
sudo pkill -TERM -u linrong -f qwen3vl-inference || true
sudo pkill -TERM -u linrong -f gcs_server || true
sleep 2
sudo pkill -KILL -u linrong -f qwen3vl-inference || true
sudo pkill -KILL -u linrong -f gcs_server || true
sudo rm -f /tmp/libtpu_lockfile
sudo rm -rf /tmp/ray
echo "cleaned $(hostname)"
'"'"''
else
  echo "[vllm-debug] Skipping stale TPU state cleanup because CLEAN_STALE_TPU_STATE=0"
fi

if [[ "$CHECK_TPU_VFIO_BUSY" == "1" ]]; then
  echo "[vllm-debug] Checking TPU VFIO devices are free"
  gcloud compute tpus tpu-vm ssh "$TPU_NAME" \
    --zone="$ZONE" \
    --worker=all \
    --command='bash -lc '"'"'
set -euo pipefail
tmp="$(mktemp)"
if sudo lsof -w /dev/vfio/* > "$tmp" 2>/dev/null; then
  echo "TPU device is still busy on $(hostname):" >&2
  cat "$tmp" >&2
  rm -f "$tmp"
  exit 1
fi
rm -f "$tmp"
echo "vfio-free $(hostname)"
'"'"''
else
  echo "[vllm-debug] Skipping TPU VFIO busy check because CHECK_TPU_VFIO_BUSY=0"
fi

if [[ "$RUN_TPU_PREFLIGHT" == "1" ]]; then
  echo "[vllm-debug] Running bounded all-worker JAX TPU preflight"
  set +e
  gcloud compute tpus tpu-vm ssh "$TPU_NAME" \
    --zone="$ZONE" \
    --worker=all \
    --command="bash -lc 'set -euo pipefail; mkdir -p \"\$HOME/tpu_logs\"; chmod 700 \"\$HOME/tpu_logs\"; export TPU_LOG_DIR=\"\$HOME/tpu_logs\"; export TPU_PREFLIGHT_HOLD_SECONDS=\"$TPU_PREFLIGHT_HOLD_SECONDS\"; timeout \"$TPU_PREFLIGHT_TIMEOUT_SECONDS\" \"\$HOME/miniconda3/envs/tunix/bin/python\" \"$PREFLIGHT_SCRIPT\"'"
  preflight_rc=$?
  set -e
  echo "[vllm-debug] JAX TPU preflight exit code: $preflight_rc"
  if [[ "$preflight_rc" != "0" ]]; then
    if [[ "$ALLOW_TPU_PREFLIGHT_FAILURE" == "1" ]]; then
      echo "[vllm-debug] Continuing despite preflight exit code because ALLOW_TPU_PREFLIGHT_FAILURE=1"
    else
      exit "$preflight_rc"
    fi
  fi
else
  echo "[vllm-debug] Skipping JAX TPU preflight because RUN_TPU_PREFLIGHT=0"
fi

PASSTHROUGH="HF_TOKEN_ENV_FILE=$REMOTE_TOKEN_ENV RUN_LOG_DIR=$RUN_LOG_DIR RUN_LOG_STEM=$RUN_LOG_STEM"
for var in model_name VLLM_DEBUG_MODEL_ID VLLM_DEBUG_PROMPT VLLM_DEBUG_MESH_SHAPE VLLM_DEBUG_MESH_AXIS_NAMES VLLM_DEBUG_MESH_SCOPE VLLM_DEBUG_MAX_MODEL_LEN VLLM_DEBUG_MAX_NUM_SEQS VLLM_DEBUG_MAX_NUM_BATCHED_TOKENS VLLM_DEBUG_MAX_GENERATION_STEPS VLLM_DEBUG_MAX_PROMPT_LENGTH VLLM_DEBUG_TENSOR_PARALLEL_SIZE VLLM_DEBUG_DATA_PARALLEL_SIZE VLLM_DEBUG_HBM_UTILIZATION VLLM_DEBUG_TEMPERATURE VLLM_DEBUG_INIT_RANDOM_WEIGHTS VLLM_DEBUG_SERVER_MODE VLLM_DEBUG_TPU_BACKEND_TYPE VLLM_DEBUG_SWAP_SPACE_GB VLLM_DEBUG_PARTICIPANT_HOLD_SECONDS TUNIX_VLLM_USE_LOCAL_TPU_DEVICE_IDS; do
  if [[ -n "${!var:-}" ]]; then
    printf -v quoted_value "%q" "${!var}"
    PASSTHROUGH="$PASSTHROUGH $var=$quoted_value"
  fi
done

REMOTE_CMD='set -euo pipefail; source "$HF_TOKEN_ENV_FILE"; mkdir -p "$RUN_LOG_DIR" "$HOME/tpu_logs"; chmod 700 "$HOME/tpu_logs"; worker_log="$RUN_LOG_DIR/${RUN_LOG_STEM}_worker_$(hostname -s 2>/dev/null || hostname).log"; exec > >(tee -a "$worker_log") 2>&1; echo "[vllm-debug] worker log: $worker_log"; export TPU_LOG_DIR="$HOME/tpu_logs"; export PYTHONPATH="/home/gs1693/repo/tunix:${PYTHONPATH:-}"; cd "/home/gs1693/repo/tunix"; "$HOME/miniconda3/envs/tunix/bin/python" "/home/gs1693/repo/tunix/examples/rl/grpo/gsm8k/debug_vllm_inference_tpu.py"'

run_probe_worker() {
  local worker="$1"
  local active_worker="$worker"
  if [[ "$worker" == "all" ]]; then
    active_worker="all"
    echo "[vllm-debug] Launching standalone vLLM stress probe on all workers"
  else
    echo "[vllm-debug] Launching standalone vLLM probe with active worker $worker and all-worker JAX participants"
  fi
  local run_passthrough="$PASSTHROUGH VLLM_DEBUG_ACTIVE_WORKER=$active_worker"
  local quoted_remote_cmd
  printf -v quoted_remote_cmd "%q" "$run_passthrough bash -lc '$REMOTE_CMD'"
  set +e
  gcloud compute tpus tpu-vm ssh "$TPU_NAME" \
    --zone="$ZONE" \
    --worker=all \
    --command="bash -lc $quoted_remote_cmd"
  local worker_rc=$?
  set -e
  echo "[vllm-debug] Active worker $worker probe exit code: $worker_rc"
  if [[ "$worker_rc" != "0" && "$VLLM_DEBUG_CONTINUE_ON_WORKER_FAILURE" != "1" ]]; then
    return "$worker_rc"
  fi
  return 0
}

if [[ "$VLLM_DEBUG_WORKERS" == "all" ]]; then
  run_probe_worker all
else
  IFS=',' read -r -a workers_to_probe <<< "$VLLM_DEBUG_WORKERS"
  for worker in "${workers_to_probe[@]}"; do
    worker="${worker//[[:space:]]/}"
    if [[ -z "$worker" ]]; then
      continue
    fi
    run_probe_worker "$worker"
  done
fi

echo "[vllm-debug] Completed. Aggregate log: $LAUNCHER_LOG"
