#!/usr/bin/env bash
# Single-host smoke-test launcher for Qwen3 GRPO simple-reward training.
#
# This runs run_qwen3_simplereward_smoke.sh directly on the current TPU VM
# host instead of launching across all TPU workers. It uses the local 4 TPU
# chips with mesh shape (1,4), which is useful for debugging correctness before
# scaling back to the full multi-host slice.
#
# Usage:
#   export HF_TOKEN=...
#   bash /home/gs1693/repo/tunix/examples/rl/grpo/gsm8k/launch_qwen3_simplereward_smoke_single_host_tpu.sh
#
# Optional:
#   Set CLEAN_STALE_TPU_STATE=0 to skip local stale-state cleanup.
#   Set CHECK_TPU_VFIO_BUSY=0 to skip the local VFIO busy-device check.
#   Set RUN_TPU_PREFLIGHT=0 to skip the local JAX TPU init check.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TRAIN_SCRIPT="$SCRIPT_DIR/run_qwen3_simplereward_smoke.sh"
PREFLIGHT_SCRIPT="$SCRIPT_DIR/jax_tpu_preflight.py"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../../.." && pwd)"
REMOTE_TOKEN_ENV="$HOME/.cache/tunix/hf_token_env"
CLEAN_STALE_TPU_STATE="${CLEAN_STALE_TPU_STATE:-1}"
CHECK_TPU_VFIO_BUSY="${CHECK_TPU_VFIO_BUSY:-1}"
RUN_TPU_PREFLIGHT="${RUN_TPU_PREFLIGHT:-1}"
TPU_PREFLIGHT_TIMEOUT_SECONDS="${TPU_PREFLIGHT_TIMEOUT_SECONDS:-120}"
TPU_PREFLIGHT_HOLD_SECONDS="${TPU_PREFLIGHT_HOLD_SECONDS:-10}"
SMOKE_MESH_SHAPE="${SMOKE_MESH_SHAPE:-"(1,4)"}"
SMOKE_MESH_AXIS_NAMES="${SMOKE_MESH_AXIS_NAMES:-"('fsdp','tp')"}"

if [[ -z "${HF_TOKEN:-}" ]]; then
  echo "HF_TOKEN must be set before launching." >&2
  echo "Example: export HF_TOKEN=hf_..." >&2
  exit 1
fi

if [[ ! -f "$TRAIN_SCRIPT" ]]; then
  echo "Smoke training script not found: $TRAIN_SCRIPT" >&2
  exit 1
fi

if [[ ! -f "$PREFLIGHT_SCRIPT" ]]; then
  echo "Preflight script not found: $PREFLIGHT_SCRIPT" >&2
  exit 1
fi

PYTHON_BIN="$HOME/miniconda3/envs/tunix/bin/python"
if [[ ! -x "$PYTHON_BIN" ]]; then
  echo "Python env not found: $PYTHON_BIN" >&2
  exit 1
fi

TPU_ENV="$(curl -sf "http://metadata.google.internal/computeMetadata/v1/instance/attributes/tpu-env" \
  -H "Metadata-Flavor: Google" || true)"
ACCELERATOR_TYPE="$(echo "$TPU_ENV" | grep "^ACCELERATOR_TYPE:" | awk '{print $2}' | tr -d "'")"
HOST_BOUNDS="$(echo "$TPU_ENV" | grep "^HOST_BOUNDS:" | awk '{print $2}' | tr -d "'")"
if [[ -n "$HOST_BOUNDS" ]]; then
  IFS=',' read -r host_x host_y host_z <<< "$HOST_BOUNDS"
  host_count=$((host_x * host_y * host_z))
  if (( host_count > 1 )); then
    cat >&2 <<EOF
This launcher only works on a single-host TPU slice, but this VM belongs to
$ACCELERATOR_TYPE with HOST_BOUNDS=$HOST_BOUNDS ($host_count hosts).

On multi-host TPU slices, JAX/libtpu initialization expects all hosts in the
slice to participate. Running only worker 0 can hang in CreateTpuSystemState
until the launcher timeout sends SIGTERM.

Use launch_qwen3_simplereward_smoke_tpu.sh on this slice, or create/use a
single-host TPU slice for this single-host launcher.
EOF
    exit 1
  fi
fi

mkdir -p "$HOME/.cache/tunix"
chmod 700 "$HOME/.cache/tunix"
{
  echo "# Generated by launch_qwen3_simplereward_smoke_single_host_tpu.sh"
  printf 'export HF_TOKEN=%q\n' "$HF_TOKEN"
} > "$REMOTE_TOKEN_ENV"
chmod 600 "$REMOTE_TOKEN_ENV"

if [[ "$CLEAN_STALE_TPU_STATE" == "1" ]]; then
  echo "[single-host smoke] Cleaning local stale Ray/libtpu state"
  current_user="$(id -un)"
  if ps -eo user=,pid=,stat=,etime=,comm=,args= | awk -v user="$current_user" '$1 == user && $0 !~ /google-cloud-cli|gcloud.py|compute tpus tpu-vm ssh/ && $5 ~ /python|vllm/ && $0 ~ /python3 -m tunix|grpo_main|vllm/ {found=1} END {exit !found}'; then
    echo "Active $current_user Tunix/vLLM process detected on $(hostname); refusing cleanup." >&2
    ps -eo user=,pid=,stat=,etime=,comm=,args= | awk -v user="$current_user" '$1 == user && $5 ~ /python|vllm/ && $0 ~ /python3 -m tunix|grpo_main|vllm/ {print}' >&2 || true
    exit 1
  fi
  sudo pkill -TERM -u linrong -f qwen3vl-inference || true
  sudo pkill -TERM -u linrong -f gcs_server || true
  sleep 2
  sudo pkill -KILL -u linrong -f qwen3vl-inference || true
  sudo pkill -KILL -u linrong -f gcs_server || true
  sudo rm -f /tmp/libtpu_lockfile
  sudo rm -rf /tmp/ray
else
  echo "[single-host smoke] Skipping stale TPU state cleanup because CLEAN_STALE_TPU_STATE=0"
fi

if [[ "$CHECK_TPU_VFIO_BUSY" == "1" ]]; then
  echo "[single-host smoke] Checking local TPU VFIO devices are free"
  tmp="$(mktemp)"
  if sudo lsof -w /dev/vfio/* > "$tmp" 2>/dev/null; then
    echo "TPU device is still busy on $(hostname):" >&2
    cat "$tmp" >&2
    rm -f "$tmp"
    exit 1
  fi
  rm -f "$tmp"
  echo "[single-host smoke] vfio-free $(hostname)"
else
  echo "[single-host smoke] Skipping TPU VFIO busy check because CHECK_TPU_VFIO_BUSY=0"
fi

if [[ "$RUN_TPU_PREFLIGHT" == "1" ]]; then
  echo "[single-host smoke] Running local JAX TPU preflight"
  mkdir -p "$HOME/tpu_logs"
  chmod 700 "$HOME/tpu_logs"
  TPU_LOG_DIR="$HOME/tpu_logs" \
  TPU_PREFLIGHT_HOLD_SECONDS="$TPU_PREFLIGHT_HOLD_SECONDS" \
    timeout "$TPU_PREFLIGHT_TIMEOUT_SECONDS" "$PYTHON_BIN" "$PREFLIGHT_SCRIPT"
else
  echo "[single-host smoke] Skipping JAX TPU preflight because RUN_TPU_PREFLIGHT=0"
fi

DATE_TIME_STR="$(date -u +%Y%m%dT%H%M%SZ)"
export TPU_WORKER_MODE=1
export HF_TOKEN_ENV_FILE="$REMOTE_TOKEN_ENV"
export SMOKE_MESH_SHAPE
export SMOKE_MESH_AXIS_NAMES
export SMOKE_LOG_STEM="${SMOKE_LOG_STEM:-qwen3_simplereward_smoke_single_host_$DATE_TIME_STR}"
export SMOKE_LOG_DIR="${SMOKE_LOG_DIR:-$REPO_ROOT/examples/rl/grpo/logs/${DATE_TIME_STR}_qwen3_simplereward_smoke_single_host}"

echo "[single-host smoke] Launching training on current host with mesh $SMOKE_MESH_SHAPE $SMOKE_MESH_AXIS_NAMES"
cd "$REPO_ROOT"
bash "$TRAIN_SCRIPT"
